version: '2.1'

services:

  web-app-test:
    extends:
      file: docker-compose.yml
      service: base-app
    command: npm run watch-test
    volumes:
      - test-deps:/code/node_modules
    environment:
      NODE_ENV: test
    links:
    - profiles-db:mongo

  travis-tests:
    extends:
      file: docker-compose.yml
      service: base-app
    command:
      sh -c "npm run git-hook && npm run upload-coverage-coveralls"
    volumes:
      - travis-test-deps:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}
    links:
    - profiles-db:mongo

  profiles-db:
    image: "nhsuk/profiles-db:${profiles_db_docker_image_tag-pr-1}"

volumes:
  test-deps:
  travis-test-deps:

