version: '2.1'

services:

  base-app:
    build:
      context: .
      args:
        NODE_ENV: development
    command: npm run watch-dev
    volumes:
      - .:/code
    environment:
      NODE_ENV: ${NODE_ENV-development}

  profiles-frontend:
    extends:
      service: base-app
    links:
    - profiles-db:mongo
    ports:
      - 3000:3000
    volumes:
      - profiles-node_modules:/code/node_modules

  profiles-db:
    image: "nhsuk/profiles-db:${profiles_db_docker_image_tag-0.3.0}"

volumes:
  profiles-node_modules:

